schema_version = 1

[agent]
framework = "langgraph"
server = "agentbricks"
deployment_name = "my-pricing-agent"

[memory_store]
name = "my-pricing-agent-abishek-memory"

[session_store]
name = "my-pricing-agent-abishek-sessions"

[tracing]
experiment_name = "/Shared/agentbricks_traces/my-pricing-agent-rdnxwd"
