command:
- uv
- run
- start-server
env:
- name: MLFLOW_TRACKING_URI
  value: databricks
- name: MLFLOW_EXPERIMENT_ID
  value: '1401602391733366'
- name: AGENT_MEMORY_STORE
  value: my-pricing-agent-abishek-memory
- name: AGENT_SESSION_STORE
  value: my-pricing-agent-abishek-sessions
- name: PIP_INDEX_URL
  value: https://pypi.org/simple/
- name: UV_INDEX_URL
  value: https://pypi.org/simple/
- name: UV_DEFAULT_INDEX
  value: https://pypi.org/simple/
- name: DATABRICKS_AGENTBRICKS_RUNTIME_STORE_LAKEBASE_BRANCH
  value: projects/databricks-internal-custom-agents/branches/production
- name: DATABRICKS_AGENTBRICKS_RUNTIME_STORE_DATABASE
  value: runtime-agent-bricks-my-pr-2171d6a4-2d83-4f8b-96bf-bccd4dac1d6d
- name: DATABRICKS_AGENTBRICKS_RUNTIME_STORE_USERNAME
  value: 22ea31af-a066-43c1-adb9-f3b62481fa58
- name: DATABRICKS_AGENTBRICKS_RUNTIME_STORE_SCHEMA
  value: databricks_agentkit_runtime
